version: 2.1
orbs:
  ruby: circleci/ruby@1.8 # use the latest Ruby orb version
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.3
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test:
          include: "spec/**/*_spec.rb"
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
